version: '2'
services: 
  api:
    image: erickwendel/nodejs-with-mongodb-example
    # build: api
    ports: 
      - 3000:4000
    environment:  
      MONGO_URL: mongo:27017
    
    depends_on: 
      - mongo
  
  mongo:
    image: mongo:3.5
    ports:
      - 27017:2017

  portainer:
      image: portainer/portainer
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      ports:

        - 5000:9000
      links:
        - mongo
        - api