version: '2'
services: 
  api:
    build: api
    ports: 
      - 3000:4000
    environment: 
      PORT: 4000
      MONGO_URL: mongodb://mongo:27017
    
    depends_on: 
      - mongo
  
  mongo:
    image: mongo:3.5
    ports:
      - 27017:2017